export enum ActiveTabs {
  LOCATIONS_WAREHOUSES = "LOCATIONS_WAREHOUSES",
  LOCATIONS_DROP_OFFS = "LOCATIONS_DROP_OFFS",
  SHIPMENTS = "SHIPMENTS",
  VEHICLES = "VEHICLES",
  SOLUTION = "SOLUTION",
}
